---
latitude: '52.070375'
longitude: "-9.574189"
map_zoom: 12
name: Demo Hotel
email: support@traveltripper.com
phone_number: 123-123-1234
address:
  street1: Lexington Ave
  state: NY
  city: New York
  zip_code: 
_hotel_id: SNBOX
_portal_id: sandbox
_root_path: https://rt3api-prd.ttaws.com
_ttweb_plugins_version: v2
default_currency: USD
default_timezone: America/New_York
__EDITABLE_FIELDS__:
  name:
    required: true
  logo:
    type: image
  email:
    type: string
  phone:
    type: string
  default_currency:
    required: true
  address:
    type: complex
    fields:
      street1:
        type: string
      state:
        type: string
      city:
        type: string
      zip_code:
        type: string
  map_zoom:
    type: integer
    latitude:
      type: float
    longitude:
      type: float
logo:
  name: Logo
  content_type: image/png
  date_added: 2018-11-09-153417
  url_thumb: http://res.cloudinary.com/traveltripperweb/image/upload/c_fill,g_faces,h_140,w_140/v1541795657/fotn8cwetoykjiarvbkm.png
  url_xsmall: http://res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_300,w_300/v1541795657/fotn8cwetoykjiarvbkm.png
  url_small: http://res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_768,w_768/v1541795657/fotn8cwetoykjiarvbkm.png
  url_medium: http://res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_992,w_992/v1541795657/fotn8cwetoykjiarvbkm.png
  url_large: http://res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_1200,w_1200/v1541795657/fotn8cwetoykjiarvbkm.png
  width: 148
  height: 64
  format: png
  url: https://res.cloudinary.com/traveltripperweb/image/upload/v1541795657/fotn8cwetoykjiarvbkm.png
  resource_type: image
  size: 2571
  s3_url: "//s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/11_16_86/media/2018-11-09-153455/fotn8cwetoykjiarvbkm.png"
  s3_url_large: "//s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/11_16_86/media/2018-11-09-153455/large_fotn8cwetoykjiarvbkm.png"
  s3_url_medium: "//s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/11_16_86/media/2018-11-09-153455/medium_fotn8cwetoykjiarvbkm.png"
  s3_url_small: "//s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/11_16_86/media/2018-11-09-153455/small_fotn8cwetoykjiarvbkm.png"
  s3_url_xsmall: "//s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/11_16_86/media/2018-11-09-153455/xsmall_fotn8cwetoykjiarvbkm.png"
  s3_url_thumb: "//s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/11_16_86/media/2018-11-09-153455/thumb_fotn8cwetoykjiarvbkm.png"
  git_file_name: _assets/image_data/device-logo.json
  path: https://res.cloudinary.com/traveltripperweb/image/upload/v1541795657/fotn8cwetoykjiarvbkm.png
  file_size: 
  alt: Logo
  caption: ''
  description: ''

