---
latitude: '52.070375'
longitude: "-9.574189"
map_zoom: 12
name: Demo Hotel
email: support@traveltripper.com
phone_number: 123-123-1234
address:
  street1: Lexington Ave
  state: NY
  city: New York
  zip_code: 
_hotel_id: SNBOX
_portal_id: sandbox
_root_path: https://rt3api-prd.ttaws.com
_ttweb_plugins_version: v2
default_currency: USD
default_timezone: America/New_York
__EDITABLE_FIELDS__:
  name:
    required: true
  logo:
    type: image
  email:
    type: string
  phone:
    type: string
  default_currency:
    required: true
  address:
    type: complex
    fields:
      street1:
        type: string
      state:
        type: string
      city:
        type: string
      zip_code:
        type: string
  map_zoom:
    type: integer
    latitude:
      type: float
    longitude:
      type: float
logo:
  name: Exhibition Hall
  content_type: image/jpeg
  date_added: 2018-11-09-153418
  url_thumb: http://res.cloudinary.com/traveltripperweb/image/upload/c_fill,g_faces,h_140,w_140/v1541795658/s9p6yajkj9s4egssmdpb.jpg
  url_xsmall: http://res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_300,w_300/v1541795658/s9p6yajkj9s4egssmdpb.jpg
  url_small: http://res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_768,w_768/v1541795658/s9p6yajkj9s4egssmdpb.jpg
  url_medium: http://res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_992,w_992/v1541795658/s9p6yajkj9s4egssmdpb.jpg
  url_large: http://res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_1200,w_1200/v1541795658/s9p6yajkj9s4egssmdpb.jpg
  width: 1440
  height: 640
  format: jpg
  url: https://res.cloudinary.com/traveltripperweb/image/upload/v1541795658/s9p6yajkj9s4egssmdpb.jpg
  resource_type: image
  size: 1067007
  s3_url: "//s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/11_16_86/media/2018-11-09-153506/s9p6yajkj9s4egssmdpb.jpg"
  s3_url_large: "//s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/11_16_86/media/2018-11-09-153506/large_s9p6yajkj9s4egssmdpb.jpg"
  s3_url_medium: "//s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/11_16_86/media/2018-11-09-153506/medium_s9p6yajkj9s4egssmdpb.jpg"
  s3_url_small: "//s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/11_16_86/media/2018-11-09-153506/small_s9p6yajkj9s4egssmdpb.jpg"
  s3_url_xsmall: "//s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/11_16_86/media/2018-11-09-153506/xsmall_s9p6yajkj9s4egssmdpb.jpg"
  s3_url_thumb: "//s3.amazonaws.com/cdn.dev-traveltripper.info/site-assets/11_16_86/media/2018-11-09-153506/thumb_s9p6yajkj9s4egssmdpb.jpg"
  git_file_name: _assets/image_data/exhibitions.json
  path: https://res.cloudinary.com/traveltripperweb/image/upload/v1541795658/s9p6yajkj9s4egssmdpb.jpg
  file_size: 
  alt: Exhibition Hall
